### ISSUE TITLE
DataFrame documentation is missing on docs.rs

### ISSUE THREAD

**Issue by vks** [Axect/Peroxide#29]
The link to it on docs.rs is dead: https://docs.rs/peroxide/0.26.4/peroxide/structure/dataframe/index.html

**Comment by Axect** [comment]
@vks Thanks for advice.
To use dataframe in peroxide, `libnetcdf` is required. Thus to construct CI is struggled work. And it's same for `O3` and `plot` features. And also I need some latex equations in document. From these reasons, I use self-hosting instead of `docs.rs` - `https://peroxide.surge.sh` or `https://peroxide.info` (mentioned in `README` & `crates.io`).

**Comment by vks** [comment]
My bad, I should have checked that you are not linking to docs.rs. Thanks for the quick reply!
